// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKunkXbTbnIEckLsWA6jn-ySLsOcl7kOo',
    appId: '1:398192964250:web:bb02c2e5379963f1cbe523',
    messagingSenderId: '398192964250',
    projectId: 'mapsense-76e7a',
    authDomain: 'mapsense-76e7a.firebaseapp.com',
    storageBucket: 'mapsense-76e7a.appspot.com',
    measurementId: 'G-PN07KH35VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdUonl7OYNOP41kZSuSWsvATbq5E3MTJA',
    appId: '1:398192964250:android:99be1ed5a08b5725cbe523',
    messagingSenderId: '398192964250',
    projectId: 'mapsense-76e7a',
    storageBucket: 'mapsense-76e7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsMDrVmjUNQaomChLPj8c_2atV7iZ-h2k',
    appId: '1:398192964250:ios:a58afe2db8eabeafcbe523',
    messagingSenderId: '398192964250',
    projectId: 'mapsense-76e7a',
    storageBucket: 'mapsense-76e7a.appspot.com',
    iosBundleId: 'com.chinrust.mapsense',
  );
}
